-- Alexandre Billard
-- 6812210
-- Lab 7



﻿CREATE SCHEMA php_project AUTHORIZATION username;
Set Search_path='php_project';

CREATE TABLE Student
(
Student_NUM varchar(10) PRIMARY KEY,
LAST_NAME VARCHAR(15),
FIRST_NAME VARCHAR(15),
STUDENT_PASS VARCHAR(15),
STREET VARCHAR(30),
CITY VARCHAR(15),
GENDER VARCHAR(6),
EMAIL VARCHAR(20)
);

CREATE TABLE COURSES
(
COURSE_NUM varchar(7) PRIMARY KEY,
COURSE VARCHAR(30)
);

CREATE TABLE GRADES
(
Student_NUM varchar(10) ,
Course_Num varchar(7),
Year integer,
Sec varchar(15),
Grade Char(2),
PRIMARY KEY (Student_num,Course_num)
);

INSERT INTO COURSES VALUES ('CSI1034','Intro to Programing');
INSERT INTO COURSES VALUES ('CSI1035','Software Usability');
INSERT INTO COURSES VALUES ('CSI2134','Databases I');
INSERT INTO COURSES VALUES ('CSI2045','Data Structures');
INSERT INTO COURSES VALUES ('CSI3056','Formal Languages');
INSERT INTO COURSES VALUES ('CSI3040','Intro to Computers');

INSERT INTO GRADES VALUES ('8352873','CSI1034',1,'FALL','A');
INSERT INTO GRADES VALUES ('8352873','CSI1035',1,'FALL','B+');
INSERT INTO GRADES VALUES ('8352873','CSI2045',1,'FALL','A+');
INSERT INTO GRADES VALUES ('8352873','CSI2134',2,'WINTER','A');
